convertable:
  - NETHERITE_SWORD
  - DIAMOND_SWORD
  - GOLDEN_SWORD
  - IRON_SWORD
  - STONE_SWORD
  - WOODEN_SWORD
  - NETHERITE_AXE
  - DIAMOND_AXE
  - GOLDEN_AXE
  - IRON_AXE
  - STONE_AXE
  - WOODEN_AXE
  - NETHERITE_PICKAXE
  - DIAMOND_PICKAXE
  - GOLDEN_PICKAXE
  - IRON_PICKAXE
  - STONE_PICKAXE
  - WOODEN_PICKAXE
  - NETHERITE_SHOVEL
  - DIAMOND_SHOVEL
  - GOLDEN_SHOVEL
  - IRON_SHOVEL
  - STONE_SHOVEL
  - WOODEN_SHOVEL
  - CROSSBOW
  - BOW
  - MACE